name: Build Release2
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: brew install ldid xz
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build
        run: |
          brew install dpkg
          chmod +x ./Resources/compile.release.action.sh
          /bin/bash -c ./Resources/compile.release.action.sh
      - name: Upload .ipa
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "chromatic.relsan.${{ env.build_timestamp }}.ipa"
          path: "build/artifact/chromatic.relsan.${{ env.build_timestamp }}.ipa"
      - name: Upload .deb
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "chromatic.rel.ci.${{ env.build_timestamp }}.deb"
          path: "build/artifact/chromatic.rel.ci.${{ env.build_timestamp }}.deb"
